### ISSUE TITLE
no data being logged

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/AppInsights-node.js#16]
Hi! I'm having trouble getting any data to show up. No data is coming across when it is run from Azure or OSX. I'm using Node.js 0.12.0 on Azure and 0.12.1 on OS X. I double checked that `APPINSIGHTS_INSTRUMENTATION_KEY` was set to the correct key both places. Any ideas. Here is the code:

https://github.com/ctaggart/SourceLink-Proxy/blob/appinsights/server.ts#L7-L11
![image](https://cloud.githubusercontent.com/assets/80104/6884436/9d2a5e26-d5a7-11e4-8807-85df4f031369.png)

**Comment by scsouthw** [comment]
Thanks for reporting the issue! It looks like the request tracking is broken because of https://github.com/joyent/node/issues/9195 

Basically node is returning something like this "::ffff:127.0.0.1" if the host system supports ipv6. 

The data collection server rejects request telemetry sent with this value since it is not valid ipv4 so no data shows up. I'll follow up with some people to see if this is something we want to fix in the data collector service or if we should try to work around it in this SDK.

**Comment by ctaggart** [comment]
Thank you! I'll update to 0.12.5.

**Comment by ctaggart** [comment]
I upgraded to 0.12.5 and I still don't see any logs in the Portal for my app. I checked again that `APPINSIGHTS_INSTRUMENTATION_KEY` was set to the correct key. I downgraded to node `0.10.x`  which installed `0.10.32` on Azure. I still see nothing. :(

**Comment by scsouthw** [comment]
I've seen request processing take up to 30 minutes sometimes. The back-end has a different queue for each type of data so it could be backed up. Could you try adding this somewhere before starting the server? Traces and Exceptions show up in ~1min. 

```javascript
appInsights.trackEvent("test");
appInsights.trackTrace("test");
appInsights.trackException("test");
```

If you still don't see anything let me know. In the browser you can do something like this to get more detailed logs, but IDK if it works in `node`.

```javascript
appInsights.config.enableDebug = true;
appInsights.config.verboseLogging = true;
```

**Comment by scsouthw** [comment]
Please let me know if you're still having issues here. I'm no longer able to repro locally so I'm very interested in understanding the issue if something is broken. Thanks again for reporting.

**Comment by ctaggart** [comment]
I put in the debug messages at startup.
``` typescript
appInsights.trackEvent("test event");
appInsights.trackTrace("test trace");
appInsights.trackException(new Error("test error"));
```

The good news is that it is working when I run it locally. This shows it not starting if I haven't set the key, then it working when I do.

![image](https://cloud.githubusercontent.com/assets/80104/7107862/0acb0e36-e128-11e4-97cb-43d954ad5a78.png)

Unfortunately, I am not getting anything reported when run it is running on Azure. I've tried hardcoding the instrumentation key. It also works locally and not on Azure. Any ideas for troubleshooting?

**Comment by ctaggart** [comment]
I switched to io.js as explained in [How to use.io.js with Azure Websites](http://azure.microsoft.com/en-us/documentation/articles/web-sites-nodejs-iojs/) and it works perfectly. =)

**Comment by scsouthw** [comment]
glad to hear, thanks for letting me know :)
